### PR TITLE
fix: fix the issue that prevent the model saving

### PR DESCRIPTION
**Pull request by Lutra-Fs**

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
image

**Comment by Lutra-Fs** [comment]
note that for the keras v3 format tfjs converter only supports it converts to layers model now, it would requires a second conversion between tfjs layer model and tfjs graph model. since we are using graph model in the website.

**Comment by Lutra-Fs** [comment]
`tensorflowjs_converter --input_format=keras_keras --output_format=tfjs_layers_model models/FNO2dLiteModel.keras tfjs_models/FNO2dLite_from_keras`

**Comment by Lutra-Fs** [comment]
seems like custom layer was not included... new error in saved model export while wrapping the model in tf.function

```
2/2 [==============================] - 10s 787ms/step - loss: 0.7757 - mean_squared_error: 0.7757
Traceback (most recent call last):
  File "/home/lutra/repos/neural_net_physics_tf/training_keras.py", line 182, in <module>
    tf.saved_model.save(model_predict, os.path.join("models", model_name))
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 1331, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 1366, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 1578, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 1504, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 877, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, object_map, defaults)
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/saved_model/save.py", line 654, in _generate_signatures
    outputs = object_map[function](**{
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 45, in __call__
    export_captures = _map_captures_to_created_tensors(
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 74, in _map_captures_to_created_tensors
    _raise_untracked_capture_error(function.name, exterior, interior)
  File "/home/lutra/.conda/envs/nn/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/saved_model_exported_concrete.py", line 98, in _raise_untracked_capture_error
    raise AssertionError(msg)
AssertionError: Tried to export a function which references an 'untracked' resource. TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
        Function name = b'__inference_signature_wrapper_7349'
        Captured Tensor = <ResourceHandle(name="Resource-7-at-0x9456bd0", device="/job:localhost/replica:0/task:0/device:GPU:0", container="Anonymous", type="tensorflow::Var", dtype and shapes : "[ DType enum: 1, Shape: [5,13] ]")>
        Trackable referencing this tensor = <tf.Variable 'fno2d_lite_model/dense/
```
with code:
```python
# maybe wrap the model in a tf.function
@tf.function(input_signature=[tf.TensorSpec(shape=(1, 64, 64, 5), dtype=tf.float32)])
def model_predict(input):
    return model(input)

tf.saved_model.save(model_predict, os.path.join("models", model_name))
```

**Review by Track07-cda — DISMISSED** [review]

**Review by Track07-cda — DISMISSED** [review]

**Review by Track07-cda — APPROVED** [review]

**Comment by Lutra-Fs** [comment]
ValueError: Unsupported Ops in the model before optimization
RFFT2D, IRFFT2D

**Pull request merged**
